name: Application Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  laravel_tests:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.4' ]
        stability: [ prefer-stable ]

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_DATABASE: forge
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    name: ${{ matrix.testsuite }} - PHP ${{ matrix.php }} - ${{ matrix.stability }}
    env:
      extensions: "dom, curl, libxml, mbstring, zip, fileinfo, json, gd, redis, pdo, bcmath"
      key: "php-extensions-tests-20250505"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          coverage: none
        env:
          runner: self-hosted

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --ignore-platform-reqs
        env:
          APP_ENV: testing

      - name: Test Suite ${{ matrix.testsuite }} Tests
        #        run: ./vendor/bin/pest --parallel --testsuite ${{ matrix.testsuite }} --colors -c phpunit.xml
        run: ./vendor/bin/testbench test
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 33306
          DB_DATABASE: forge
          DB_USERNAME: root
          DB_PASSWORD: secret
          REDIS_HOST: 127.0.0.1
          TYPESENSE_HOST: 127.0.0.1
          TYPESENSE_PORT: 8108

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs